name: ItemLimiter
version: '1.1-SNAPSHOT'
main: net.saturn.itemlimiter.ItemLimiter
api-version: '1.21'
load: STARTUP
authors: [ ___Pumpkinn ]
description: A minecraft plugin that let's to limit any item in the players inventory

commands:
  itemlimit:
    description: Manage item limitations
    usage: /<command> <add|remove|list|check|clear> [item]
    permission: itemlimiter.admin
    aliases: [ il, limititem, itemban ]

permissions:
  itemlimiter.admin:
    description: Allows use of admin commands
    default: op